# Generated by Django 4.1 on 2022-08-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsgariUcret',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('donem', models.DateField()),
                ('gunluk_altsinir', models.FloatField()),
                ('gunluk_ustsinir', models.FloatField()),
                ('aylik_altsinir', models.FloatField()),
                ('aylik_ustsinir', models.FloatField()),
            ],
        ),
    ]
